---
- name: vmdeneme
  hosts: localhost
  connection: local
  gather_facts: no
  handlers:
    - name: Restart Apache
      service:
        name: httpd
        state: restarted
  tasks:
  - name: new vm
    vmware_guest:
      hostname: 192.168.1.3
      username: bogachan.bilgin@konsalt.info
      password: Qq123456
      validate_certs: no
      name: Denemebgc
      template: Denemebgc1
      datacenter: Konsalt-MESA
      folder: /RedHat/RHEL
      state: poweredon
      networks:
      - name: VM Network
        ip: 192.168.73.1/16
        gateway: 192.168.0.1
        netmask: 255.255.255.0
        domain: konsalt.info
        dns_servers: 192.168.1.10
      wait_for_ip_address: yes
  - name: Install Apache
    package:
      name: httpd
      state: present

  - name: Configure Apache to Listen on Port 8888
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^Listen '
      line: 'Listen 8888'
      notify: Restart Apache
  
  - name: Sending an e-mail using Gmail SMTP servers
    community.general.mail:
      host: smtp.gmail.com
      port: 587
      username: mailer@konsalt.com.tr
      password: Kon123_5!
      to: bogachan<bogachan.bilgin@konsalt.com.tr>
      subject: Ansible-report
      body: mesaj
      enbaletls: true
      lsversion: STARTTLS
